name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    needs: test
    if: ${{ needs.test.outputs.status == 'success' }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'

    - name: Install system dependencies
      run: |
        make lilypond

    - name: Install R dependencies
      run: |
        make deps

    - name: Build
      run: make run