name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    outputs:
      status: ${{ job.status }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'

    - name: Install system dependencies
      run: |
        make lilypond

    - name: Install R dependencies
      run: |
        make deps

    - name: Run tests
      run: make test