name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set permissions for the workflow
permissions:
  contents: read
  packages: read
  actions: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'

    - name: Install LilyPond (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install lilypond

    - name: Install LilyPond (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y lilypond

    - name: Install system dependencies
      run: |
        make dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'

    - name: Install LilyPond (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install lilypond

    - name: Install LilyPond (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y lilypond

    - name: Install system dependencies
      run: |
        make dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: make run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}